"""EirView backend core package."""

from backend.activity import (
    check_inactivity,
    get_workout_summary,
    get_workouts,
    log_workout,
    workout_targets,
)
from backend.alerts import (
    check_alerts,
    check_critical_values,
    notify_doctor,
    process_alerts,
    send_doctor_alert,
)
from backend.database import (
    DB_PATH,
    create_user,
    get_all_users,
    get_db,
    get_meals,
    get_posture_history,
    get_profile,
    get_profile_dict,
    get_recent_meals_db,
    get_risk_projections,
    get_user,
    get_water_today,
    init_db,
    log_agent_action,
    log_meal,
    log_posture,
    log_spotify,
    log_water,
    save_risk_projections,
    seed_data,
    update_profile_fields,
    upsert_profile,
)
from backend.family import create_family, get_family_dashboard, join_family
from backend.formulas import (
    calculate_bio_age,
    mental_wellness_score,
    nutrition_targets,
    project_risk,
    rank_impact,
    score_meal,
    simulate_habit_change,
)
from backend.gamification import (
    get_gamification,
    get_gamification_summary,
    get_leaderboard,
    log_action,
    process_action,
)
from backend.reminder_engine import check_reminders, get_reminders
from backend.specialists import check_specialist_needs, check_specialists

__all__: list[str] = [
    "DB_PATH",
    "calculate_bio_age",
    "check_alerts",
    "check_critical_values",
    "check_inactivity",
    "check_reminders",
    "check_specialist_needs",
    "check_specialists",
    "create_family",
    "create_user",
    "get_all_users",
    "get_db",
    "get_family_dashboard",
    "get_gamification",
    "get_gamification_summary",
    "get_leaderboard",
    "get_meals",
    "get_posture_history",
    "get_profile",
    "get_profile_dict",
    "get_recent_meals_db",
    "get_reminders",
    "get_risk_projections",
    "get_user",
    "get_water_today",
    "get_workout_summary",
    "get_workouts",
    "init_db",
    "join_family",
    "log_action",
    "log_agent_action",
    "log_meal",
    "log_posture",
    "log_spotify",
    "log_water",
    "log_workout",
    "mental_wellness_score",
    "notify_doctor",
    "nutrition_targets",
    "process_action",
    "process_alerts",
    "project_risk",
    "rank_impact",
    "save_risk_projections",
    "score_meal",
    "seed_data",
    "send_doctor_alert",
    "simulate_habit_change",
    "update_profile_fields",
    "upsert_profile",
    "workout_targets",
]
